[package]
name = "fcp"
version = "0.1.0"
authors = ["Kevin Svetlitski <kevin_svetlitski@berkeley.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.19.1"
rayon = "1.5.0"

[dev-dependencies]
criterion = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4.0"


[[bench]]
name = "baseline_benchmark"
harness = false
